version: '2'

services:
  players:
    build:
      context: canned-events
      args:
        FILE: player-events.yaml
    environment:
      SERVICE: players
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

  matchmaker:
    build:
      context: canned-events
      args:
        FILE: matchmaker-events.yaml
    environment:
      SERVICE: matchmaker
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

  gameplay:
    build:
      context: canned-events
      args:
        FILE: gameplay-events.yaml
    environment:
      SERVICE: gameplay
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

  scoring:
    build: scoring
    environment:
      WEBSOCKET: ws://172.17.0.1:9999
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
