version: '2'

services:
  players:
    build:
      context: canned-events
      args:
        FILE: player-events.yaml
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

  matches:
    build:
      context: canned-events
      args:
        FILE: match-events.yaml
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

  scoring:
    build: scoring
    environment:
      WEBSOCKET: ws://172.17.0.1:9999
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
