version: '2'

services:
  players:
    build:
      context: canned-events
      args:
        FILE: player-events.yaml
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    depends_on:
      - fluentd

  matches:
    build:
      context: canned-events
      args:
        FILE: match-events.yaml
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    depends_on:
      - fluentd

  fluentd:
    build: fluentd
    ports:
      - '8080:8080'
      - '24224:24224'

  fluentd-sink:
    build: sink
    environment:
      WEBSOCKET: ws://fluentd:8080
    depends_on:
      - fluentd
